version: "3.1"
services:
  seata-server:
    image: seataio/seata-server:${SEATA_VERSION}
    container_name: seata-server
    hostname: seata-server
    command: -h 192.168.50.180
    restart: always
    ports:
      - "8091:8091"
    environment:
      - STORE_MODE=db
      # 指定seata服务启动端口
      - SEATA_PORT=8091
      # 注册到nacos上的ip。客户端将通过该ip访问seata服务。
      # 注意公网ip和内网ip的差异。
      - SEATA_IP=127.0.0.1
    volumes:
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/timezone"
      - "./seata-server/resources/application.yml:/seata-server/resources/application.yml"