version: '3.1'

services:

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    restart: always
    ports:
      - "8880:80"
    volumes:
      - ./etc/nginx/html:/usr/share/nginx/html
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d
      - ./etc/nginx/log:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ALLURE_love921
      - MYSQL_DATABASE=spring-boot-scaffold
    ports:
      - "3306:3306"
    volumes:
      - ./etc/mysql/data:/var/lib/mysql
      - ./etc/mysql/conf.d:/etc/mysql/conf.d

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./etc/redis/data:/data:rw
      - ./etc/redis/config/redis.conf:/usr/local/etc/redis/redis.conf

  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: mongo
    command: --auth
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=icuxika
      - MONGO_INITDB_ROOT_PASSWORD=ALLURE_love921
    ports:
      - "27017:27017"
    volumes:
      - ./etc/mongo/db:/data/db
      - ./etc/mongo/logs:/data/logs
      - ./etc/mongo/configdb:/data/configdb

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./etc/rabbitmq/data:/var/lib/rabbitmq

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:${KIBANA_VERSION}
    container_name: kibana
    restart: always
    environment:
      - "SERVER_NAME=kibana"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
