server:
  port: 8910

spring:
  application:
    name: @artifactId@

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:driftwood-cloud}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

    stream:
      rocketmq:
        binder:
          name-server: ${ROCKETMQ_HOST:127.0.0.1}:${ROCKETMQ_PORT:9876}
        bindings:
          websocketMessageConsumer-out-0:
            producer:
              group: default_producer_group
          websocketMessageConsumer-in-0:
            consumer:
              messageModel: BROADCASTING
      bindings:
        websocketMessageConsumer-out-0:
          destination: websocket_message
        websocketMessageConsumer-in-0:
          destination: websocket_message
          group: default_consumer_group

  config:
    import:
      - nacos:application-@profiles.active@.yml?refreshEnabled=false
      - nacos:${spring.application.name}-@profiles.active@.yml?refreshEnabled=false
      - nacos:resource-server.yml?refreshEnabled=false

logging:
  level:
    com.icuxika.framework.service.websocket.config.ManageableWebSocketSession: TRACE