server:
  port: 8915

spring:
  application:
    name: @artifactId@

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

  config:
    import:
      - nacos:application-@profiles.active@.yml?refreshEnabled=false
      - nacos:${spring.application.name}-@profiles.active@.yml?refreshEnabled=false
      - nacos:resource-server.yml?refreshEnabled=false

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        enabled: false
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5