server:
  port: 8915

spring:
  application:
    name: @artifactId@

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

  config:
    import:
      - nacos:application-@profiles.active@.yml?refreshEnabled=false
      - nacos:${spring.application.name}-@profiles.active@.yml?refreshEnabled=false
      - nacos:resource-server.yml?refreshEnabled=false

  ai:
    chat:
      client:
        observations:
          include-input: false
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        enabled: true
        options:
          model: qwen-max
          top_p: 0.7
    ollama:
      base-url: http://localhost:11434
      chat:
        enabled: false
        model: qwen2.5
      embedding:
        enabled: false
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        enabled: false
        options:
          model: deepseek-chat
      embedding:
        enabled: false

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG