server:
  port: 8913

spring:
  application:
    name: @artifactId@

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

  config:
    import:
      - nacos:application-@profiles.active@.yml?refreshEnabled=false
      - nacos:${spring.application.name}-@profiles.active@.yml?refreshEnabled=false
      - nacos:resource-server.yml?refreshEnabled=false

flowable:
  idm:
    app:
      admin:
        user-id: admin
        password: test
        first-name: driftwood
        last-name: driftwood

management:
  health:
    ldap:
      enabled: false

logging:
  level:
    org.flowable: INFO