server:
  port: 8912

spring:
  application:
    name: @artifactId@

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:driftwood-cloud}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

  config:
    import:
      - nacos:application-@profiles.active@.yml?refreshEnabled=false
      - nacos:${spring.application.name}-@profiles.active@.yml?refreshEnabled=false
      - nacos:resource-server.yml?refreshEnabled=false

minio:
  endpoint: http://localhost:9001
  accessKey: driftwood
  secretKey: driftwood
