server:
  port: 8912

minio:
  endpoint: http://localhost:9001
  accessKey: driftwood
  secretKey: driftwood

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 512MB # ?????????
      max-request-size: 512MB # ????????????
