server:
  port: 8904

spring:
  datasource:
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: driftwood
        login-password: driftwood
      filters: stat,wall,log4j2
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: driftwood-cloud:8899

logging:
  level:
    com.alibaba.nacos.client.*: ERROR
    com.icuxika.framework.object.modules.file.feign.FileClient: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: full
  circuitbreaker:
    enabled: true