server:
  port: 8903

spring:
  application:
    name: @artifactId@

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

  config:
    import:
      - nacos:application-@profiles.active@.yml?refreshEnabled=false
      - nacos:${spring.application.name}-@profiles.active@.yml?refreshEnabled=false
      - nacos:resource-server.yml?refreshEnabled=false

ext:
  model-persistence-type: MyBatis

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
