server:
  port: 8907

seata:
  enabled: true
  tx-service-group: seata-service
  service:
    vgroup-mapping:
      seata-service: default
    grouplist:
      default: ${SEATA_HOST:127.0.0.1}:${SEATA_PORT:8091}
    disable-global-transaction: false

logging:
  level:
    io.seata: INFO
