server:
  port: 8902

spring:
  application:
    name: @artifactId@

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:driftwood-cloud}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

  config:
    import:
      - nacos:application-@profiles.active@.yml?refreshEnabled=false
      - nacos:${spring.application.name}-@profiles.active@.yml?refreshEnabled=false
      - nacos:resource-server.yml?refreshEnabled=false

feign:
  circuitbreaker:
    enabled: true
#  okhttp:
#    enabled: true

logging:
  level:
    com.alibaba.nacos.client.*: ERROR
    com.icuxika.admin.feign.AuthClient: DEBUG

file:
  local:
    enable: true
    base: /Users/icuxika/temp/driftwood

open:
  auth:
    callback-template: callback
    error-callback-template: errorCallback
    notification-page: http://127.0.0.1:3000/
    github:
      client-id: 4efe670ba6206abdf3ad
      client-secret: a4dd39dfa16526b536bbde457d7139a2cfbfdab7
    gitee:
      client-id: 1
      client-secret: 2
    wechat-mini:
      client-id: 1
      client-secret: 2
    alipay-mini:
      client-id: 1
      client-secret: 2
