server:
  port: 8902

feign:
  circuitbreaker:
    enabled: true
  okhttp:
    enabled: true

spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: driftwood-cloud:8899
