server:
  port: 8901

spring:
  application:
    name: @artifactId@

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:driftwood-cloud}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

  config:
    import:
      - nacos:application-@profiles.active@.yml?refreshEnabled=false
      - nacos:${spring.application.name}-@profiles.active@.yml?refreshEnabled=false

  sql:
    init:
      username: root
      password: ALLURE_love921
      schema-locations:
        - classpath:sql/oauth2-authorization-schema.sql
        - classpath:sql/oauth2-authorization-consent-schema.sql
        - classpath:sql/oauth2-registered-client-schema.sql
      mode: never

logging:
  level:
    com.alibaba.nacos.client.*: ERROR
    com.icuxika.framework.object.modules.user.feign.UserClient: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true
  sentinel:
    enabled: false
    default-rule: default
    rules:
      default:
        - grade: 2
          count: 1
          timeWindow: 15
          statIntervalMs: 3000
          minRequestAmount: 1