server:
  port: 8901

spring:
  application:
    name: @artifactId@

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

  config:
    import:
      - nacos:application-@profiles.active@.yml?refreshEnabled=false
      - nacos:${spring.application.name}-@profiles.active@.yml?refreshEnabled=false

  sql:
    init:
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:ALLURE_love921}
      schema-locations:
        - classpath:sql/oauth2-authorization-schema.sql
        - classpath:sql/oauth2-authorization-consent-schema.sql
        - classpath:sql/oauth2-registered-client-schema.sql
      mode: never
