server:
  port: 8901

spring:
  sql:
    init:
      username: root
      password: ALLURE_love921
      schema-locations:
        - classpath:sql/oauth2-authorization-schema.sql
        - classpath:sql/oauth2-authorization-consent-schema.sql
        - classpath:sql/oauth2-registered-client-schema.sql
      mode: never
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8899

logging:
  level:
    com.alibaba.nacos.client.*: ERROR
    com.icuxika.modules.user.feign.UserClient: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true
  sentinel:
    enabled: false
    default-rule: default
    rules:
      default:
        - grade: 2
          count: 1
          timeWindow: 15
          statIntervalMs: 3000
          minRequestAmount: 1