version: "3.1"
services:
  minio:
    image: minio/minio:${MINIO_VERSION}
    container_name: minio
    command: server /data --console-address ":9000" -address ":9001"
    restart: always
    ports:
      - "9001:9001"
      - "8884:9000"
    environment:
      - MINIO_ROOT_USER=${ROOT_USERNAME}
      - MINIO_ROOT_PASSWORD=${ROOT_PASSWORD}
    volumes:
      - ./data:/data