version: "3.1"
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:${XXL_JOB_ADMIN_VERSION}
    container_name: xxl-job-admin
    restart: always
    ports:
      - "8883:8080"
    environment:
      - PARAMS=--spring.datasource.url=jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.password=${MYSQL_PASSWORD}
    volumes:
      - ./tmp:/data/applogs