version: "3.1"
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxl-job-admin
    restart: always
    ports:
      - "8883:8080"
    environment:
      - PARAMS=--spring.datasource.url=jdbc:mysql://192.168.50.180:3306/driftwood-cloud-xxl-job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.password=ALLURE_love921
    volumes:
      - ./tmp:/data/applogs