server:
  port: 8903

spring:
  application:
    name: @artifactId@

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:driftwood-cloud}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

  config:
    import:
      - nacos:application-@profiles.active@.yml?refreshEnabled=false
      - nacos:${spring.application.name}-@profiles.active@.yml?refreshEnabled=false
      - nacos:nacos-config.yml?refreshEnabled=true

logging:
  level:
    com.alibaba.nacos.client.*: TRACE
#    com.alibaba.nacos.client.naming.beat.*: INFO